# Generated by Django 3.0.6 on 2020-05-10 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200509_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='imagen/default.jpg', upload_to='imagen'),
        ),
    ]
