# Generated by Django 3.0.6 on 2020-05-10 15:30

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_legales'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sobremi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saludo', models.CharField(max_length=150)),
                ('content', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
